// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ingest.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppName     = "user-service"
// ServiceName  = "user"
type LogSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSource) Reset() {
	*x = LogSource{}
	mi := &file_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSource) ProtoMessage() {}

func (x *LogSource) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSource.ProtoReflect.Descriptor instead.
func (*LogSource) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *LogSource) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *LogSource) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type IngestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Source         *LogSource             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	TraceId        string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Endpoint       string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	HttpStatus     string                 `protobuf:"bytes,4,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                             // "request" | "response"
	Direction      string                 `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`                                   // "inbound" | "outbound"
	MetadataJson   string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`         // optional, JSON-encoded object
	RawPayloadJson string                 `protobuf:"bytes,8,opt,name=raw_payload_json,json=rawPayloadJson,proto3" json:"raw_payload_json,omitempty"` // optional, JSON-encoded object
	PayloadJson    string                 `protobuf:"bytes,9,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`            // optional, JSON-encoded object
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetSource() *LogSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *IngestRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IngestRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *IngestRequest) GetHttpStatus() string {
	if x != nil {
		return x.HttpStatus
	}
	return ""
}

func (x *IngestRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IngestRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *IngestRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *IngestRequest) GetRawPayloadJson() string {
	if x != nil {
		return x.RawPayloadJson
	}
	return ""
}

func (x *IngestRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_ingest_proto protoreflect.FileDescriptor

const file_ingest_proto_rawDesc = "" +
	"\n" +
	"\fingest.proto\x12\alogging\"I\n" +
	"\tLogSource\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"\xb7\x02\n" +
	"\rIngestRequest\x12*\n" +
	"\x06source\x18\x01 \x01(\v2\x12.logging.LogSourceR\x06source\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vhttp_status\x18\x04 \x01(\tR\n" +
	"httpStatus\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\x12(\n" +
	"\x10raw_payload_json\x18\b \x01(\tR\x0erawPayloadJson\x12!\n" +
	"\fpayload_json\x18\t \x01(\tR\vpayloadJson\"D\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2J\n" +
	"\rIngestService\x129\n" +
	"\x06Ingest\x12\x16.logging.IngestRequest\x1a\x17.logging.IngestResponseB'Z%external-service-log/internal/grpc/pbb\x06proto3"

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData []byte
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)))
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ingest_proto_goTypes = []any{
	(*LogSource)(nil),      // 0: logging.LogSource
	(*IngestRequest)(nil),  // 1: logging.IngestRequest
	(*IngestResponse)(nil), // 2: logging.IngestResponse
}
var file_ingest_proto_depIdxs = []int32{
	0, // 0: logging.IngestRequest.source:type_name -> logging.LogSource
	1, // 1: logging.IngestService.Ingest:input_type -> logging.IngestRequest
	2, // 2: logging.IngestService.Ingest:output_type -> logging.IngestResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
